language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - invoke test
  # Install SSLyze as a module and run the sample script
  - python setup.py install
  - cd docs  # Switch folder to avoid conflicts between ./sslyze and the installed sslyze module
  - python ../api_sample.py
